---
- name: Check for newrelic_license_key
  fail:
    msg: "newrelic_license_key has not been defined"
  when: newrelic_license_key|default(False) == False

- name: Check for newrelic_appname
  fail:
    msg: "newrelic_appname has not been defined"
  when: newrelic_appname|default(False) == False

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: default.yml
  when: newrelic_loaded_os_family|default(False) == False

- name: Configure New Relic PHP Agent
  template:
    src: newrelic.ini.j2
    dest: /etc/php5/conf.d/newrelic.ini
    group: root
    owner: root
    mode: 0640
  notify:
    - Run New Relic Installer
  when: newrelic_loaded_os_family|default(False) != False